### ISSUE TITLE
Wiql-editor playground no longer working in Edge

### ISSUE THREAD

**Issue by hgran** [ostreifel/wiql-editor#22]
Using version 2.0.76 in TFS 2018 Update 3 the playground functionality no longer works in Edge.
It will hang on load. It works uysing Chrome.

In the JavaScript console we get:
```
at ./scripts/getCurrentTheme.ts (http://tfs.company.com:8080/tfs/_apis/public/gallery/publisher/ottostreifel/extension/wiql-editor/2.0.76/assetbyname/dist/playground.js:357:1)
   at __webpack_require__ (http://tfs.company.com:8080/tfs/_apis/public/gallery/publisher/ottostreifel/extension/wiql-editor/2.0.76/assetbyname/dist/playground.js:20:12)
   at eval code (eval code:10:22)
   at ./scripts/wiqlEditor/wiqlEditor.tsx (http://tfs.company.com:8080/tfs/_apis/public/gallery/publisher/ottostreifel/extension/wiql-editor/2.0.76/assetbyname/dist/playground.js:729:1)
   at __webpack_require__ (http://tfs.company.com:8080/tfs/_apis/public/gallery/publisher/ottostreifel/extension/wiql-editor/2.0.76/assetbyname/dist/playground.js:20:12)
   at eval code (eval code:6:22)
   at ./scripts/wiqlPlayground/playground.ts (http://tfs.company.com:8080/tfs/_apis/public/gallery/publisher/ottostreifel/extension/wiql-editor/2.0.76/assetbyname/dist/playground.js:741:1)
   at __webpack_require__ (http://tfs.company.com:8080/tfs/_apis/public/gallery/publisher/ottostreifel/extension/wiql-editor/2.0.76/assetbyname/dist/playground.js:20:12)
   at Anonymous function (http://tfs.company.com:8080/tfs/_apis/public/gallery/publisher/ottostreifel/extension/wiql-editor/2.0.76/assetbyname/dist/playground.js:84:11)
   at Anonymous function (http://tfs.company.com:8080/tfs/_apis/public/gallery/publisher/ottostreifel/extension/wiql-editor/2.0.76/assetbyname/dist/playground.js:1:584)```

**Comment by ostreifel** [comment]
Fix is now public

**Comment by hgran** [comment]
Thank you for fixing it so quickly, I have verified that it now works in our TFS as well.
